[package]
name = "atomics"
version = "0.1.0"
edition = "2021"

[dependencies]
std-semaphore = "0.1.0"

[[bin]]
name = "buffer"
path = "src/buffer.rs"

[[bin]]
name = "drop_no_drop"
path = "src/drop_no_drop.rs"
